substitutions:
  OTA_PASSWORD: "OwRKb2kXFQT0NFhk7/ydpE+YCV+4ytk0"
  PROD_MANIFEST_URL: "https://morganmlg.com/BucketRainGauge/manifest.json"
  BETA_MANIFEST_URL: "https://morganmlg.com/BucketRainGauge/manifest-beta.json"
  WEB_USERNAME: "esphome"
  WEB_PASSWORD: "esphome"
  AP_SSID: "Bucket Rain Gauge"
  AP_PASSWORD: "esphome-fallback"

esphome:
  name: bucket-rain-gauge
  friendly_name: "Bucket Rain Gauge"
  comment: "ESP32-C3 tipping-bucket rain gauge"
  name_add_mac_suffix: true
  project:
    name: "DoYouHost.BucketRainGauge"
    version: "dev"

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf
    version: recommended

dashboard_import:
  package_import_url: github://DoYouHost/esphome-bucket-rain-gauge/bucket-rain-gauge.yml@main
  import_full_config: false

packages:
  DoYouHost/ESPHomeTemplates:
    url: https://github.com/DoYouHost/ESPHomeTemplates
    files:
      - basic.yaml
      - debug.yaml
      - buttons.yaml
      - updateBetaProdStaging.yaml
      - wifiInfo.yaml
    ref: main
    refresh: 0d

wifi:
  reboot_timeout: 15min
  enable_btm: true
  enable_rrm: true
  ap:
    ssid: "${AP_SSID}"
    password: "${AP_PASSWORD}"
  on_connect:
    - script.execute: improv_disable_grace
  on_disconnect:
    - script.stop: improv_disable_grace
    - lambda: "id(improv_ble).start();"

captive_portal:

improv_serial:

esp32_improv:
  id: improv_ble
  authorizer: none

provisioning:
  timeout: 5min

api:
  reboot_timeout: 15min
  encryption:

ota:
  - platform: esphome
    password: "${OTA_PASSWORD}"

script:
  - id: improv_disable_grace
    mode: restart
    then:
      - delay: 10s
      - lambda: "id(improv_ble).stop();"
